### ISSUE TITLE
When msincomplete is NA

### ISSUE THREAD

**Issue by Joe-Hilgard** [raklein/ml4#2]
Exclusion rules 1, 2, and 3 indicate that participants should be excluded if they do not complete both writing prompts. Only 6 participants are explicitly marked as not having completed both prompts, but a further 943 have an NA in this column. 

Currently those 943 participants are treated as having completed both prompts. It seems like it would be inappropriate to include these participants, as we do not know whether or not they completed the prompts, right? Would it be possible to consult the writing responses and change these NAs to explicit 0s and 1s?

**Comment by stephensrmmartin** [comment]
We must have been looking at this at the same time.

It's actually more nefarious than this.

Exclusion set 1:
```
ds.1 <- ds[complete.cases(ds[,c(prous, antius)]) & ds$msincomplete == 0 & !is.na(ds$msincomplete),]
```
Returns N=1325. The reported number: 2220.
When `!is.na(...)` is not included, then you wind up having ds$incomplete == 0, on NA values. If you use a logical expression on NA, it returns NA: `c(1,2,NA) == 1 # c(TRUE, FALSE, NA)`. If you subset by NA, then you get an "NA" back: `ds[c(1,2,NA) == 1, ] # Dataframe with one normal row, and one row full of NA`
Excluding the NAs gets you the N=2220, but a large chunk of that is just NA. So the paper reports an N=2220 analysis, but only actually can use a maximum of 1325.

Exclusion set 2:
```
ds.2 <- ds.1[ds.1$race == 1 & ds.1$countryofbirth == 1 & !is.na(ds.1$race) & !is.na(ds.1$countryofbirth), ] # Should-be-correct

```
This is executed across the whole dataset (including those with expert == 0). This returns N = 524, not 1874 (I actually could not figure out how 1874 was observed; I tried several things).
This has the same problem. Excluding the `!is.na(...)` statements will cause NA values in the logical vector, which when subsetted by returns the data rows where TRUE is met, but also NA rows where NA was returned.

Exclusion set 3:
```
ds.3 <- ds.2[ds.2$americanid >= 7 & !is.na(ds.2$americanid), ] # Should-be-Correct
```
N=232. Same issue as before.

Importantly, summary statistics should have red-flagged this. If you look at the table counts of race and countryofbirth:
```
> table(ds$race,useNA="always")

   0    1    2    3    4    5    6 <NA> 
   1  914  120   36  222   20  114  854 
```
```
> table(ds$countryofbirth,useNA="always")

   1    2    4    6 <NA> 
1201  139    1    1  939 

```
Then if you exclude both race *and* countryofbirth that don't match one value, the maximum N you can possibly have is 914.

So ultimately, the paper reports much, much higher N than is actually used by the analysis - All the NA values wind up being filled with NA data. `ds[c(1,2,NA),]` would return a 3-row dataset, where the third row is nothing but NA values. So the exclusion dataset models must necessarily have a much, much lower N, simply because all the NAs in exclusion criteria have fully NA data.

The analysis without exclusion criteria are not, to my knowledge, affected by this.

**Comment by Joe-Hilgard** [comment]
Yes, I noticed race and country of origin and american-identification NAs leaking back into the dataset in exclusion 2 and 3, which lead to my [pull request](https://github.com/raklein/ml4/pull/1) that I hope will fix it.

With regard to exclusion 1, currently the implementation is `(data$msincomplete == 0 | is.na(data$msincomplete)` (see [line136](https://github.com/raklein/ml4/blob/master/002_ml4analysis.R#L136)). Thanks to the parentheses, that will evaluate as TRUE if msincomplete is NA:
```
> NA == 0 | is.na(NA)
[1] TRUE
```

Dr. Klein's going to double-check in the morning whether that's a bug or a feature. I'm just leaving the GitHub issue here so there's a record of the question and its ultimate decision.

**Comment by stephensrmmartin** [comment]
```
n|expert, exc1 = 719; n|exc1, combined = 2146

n|expert, exc2 = 390; n|exc2, combined = 1817

n|expert, exc3 = 232; n|exc3, combined = 1659
```
This is how I assume it is intended to be ^

n|expert, exc1 means "n after applying exc1 criteria only on expert locations"
n|exc1, combined means "n after the above, but combining it with the non-expert locations (the only filter for those is that the prous-antius measures have no missings).

**Comment by raklein** [comment]
Thanks both, I've merged Joe's pull request and also adjusted the msincomplete exclusion to:

((data$msincomplete == 0 & !is.na(data$msincomplete)) | data$expert == 0 | data$source == "uwmadison_expert") 

P completed both prompts (now excluding NAs), or site is a non-expert site where this exclusion did not apply (as per pre-reg), or source is uwmadison_expert: that sample left the msincomplete variable NA instead of coding "0" or "1". However, they took detailed notes at the time and reported that no responses were abnormal. In addition, at the other expert sites that coded this information, none reported a case where a participant left both responses blank (cnj had a few NAs, which we now exclude). Let me know if you disagree, but I think that's the most justifiable approach -- and I'll note this as well.

I'll also propose we report the n (after exclusions with the various rules) separately for the In House and Author Advised sites, as that was not clear. Sound good?

**Comment by Joe-Hilgard** [comment]
>
> However, they took detailed notes at the time and reported that no
> responses were abnormal.


Sounds fine, but one might still wonder whether "no responses were
abnormal" means "no responses were incomplete". If it's indeed the case
that no responses were incomplete, it'd be nice to code that on the raw
data rather than kludge it in during preprocessing.

**Comment by raklein** [comment]
Just to update, here's what I'm getting for n after exclusions with the new code (after going back and implementing what we missed in the pre-reg: a date exclusion, and the N < 60 exclusion -- and also fixing the NA bug and making the msincomplete exclusion more transparent):
Excl 1: In House: 851, AA: 699
Excl 2: IH: 851 (unchanged) AA: 378
Excl 3: IH: 851 (unchanged) AA: 225
